[package]
name = "hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
hello-world-methods = { path = "methods" }
risc0-zkvm = "3.0.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
