name: check
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: format
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.formatting

      #- name: r0vm
      #  run: nix build -L --no-link --show-trace .#packages.x86_64-linux.r0vm

      #- name: risc0-rust
      #  run: nix build -L --no-link --show-trace .#packages.x86_64-linux.risc0-rust

      - name: template
        run: |
          git config --global init.defaultBranch master
          ./scripts/use-template.sh
